In [2]:
import numpy as np


#4. TO - DO - Task
Please complete all the problem listed below.
###4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [9]:
# 1
a=np.empty((2,2))
print("1. \n",a)

# 2
b = np.ones((4, 2))
print("2. \n",b)

# 3
filled_array = np.full((4, 4), fill_value=6)
print( "3. \n",filled_array)

# 4
reference_array = np.array([[5, 3], [2, 7], [6, 9]])
zeros_like_array = np.zeros_like(reference_array)
print("4. \n",zeros_like_array)

# 5
ones_like_array = np.ones_like(reference_array)
print( "5. \n",ones_like_array)

# 6
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print( "6. \n",numpy_array)



1. 
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]
2. 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. 
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]
4. 
 [[0 0]
 [0 0]
 [0 0]]
5. 
 [[1 1]
 [1 1]
 [1 1]]
6. 
 [1 2 3 4]


###4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [11]:
# 1
array_range = np.arange(10, 50)
print("1. \n", array_range)

# 2
reshaped_matrix = np.arange(9).reshape((3, 3))
print("2. \n", reshaped_matrix)


# 3
identityMatrix = np.eye(3)
print("3. \n", identityMatrix)

# 4
random_array = np.random.random(30)
mean_array_value = random_array.mean()
print("4. \n", random_array)
print("Mean value of random array:", mean_array_value)

# 5
rand = np.random.random((10, 10))
min_value = rand.min()
max_value = rand.max()
print("5. \n", rand)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6
zero_array = np.zeros(10)
zero_array[4] = 1
print("6. \n", zero_array)

# 7
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("7. \n", reversed_array)

# 8
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("8. \n", border_array)

#9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. \n", checkerboard)

1. 
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. 
 [0.53645075 0.01709967 0.93412192 0.61137379 0.6373054  0.38190624
 0.31340489 0.51818841 0.56458184 0.21827328 0.0191719  0.16236801
 0.02934739 0.9229619  0.4704527  0.70186583 0.57673244 0.02184072
 0.56488303 0.44204507 0.02008032 0.10274654 0.95635943 0.61885008
 0.82853119 0.11489479 0.89702769 0.30109594 0.70425221 0.42670191]
Mean value of random array: 0.4538305088737521
5. 
 [[0.94228368 0.25586607 0.80168267 0.55875495 0.59898547 0.80122046
  0.68224456 0.40292069 0.42917799 0.5253618 ]
 [0.8704402  0.76236374 0.06926095 0.93550045 0.02463428 0.35442051
  0.70136693 0.49375896 0.18013269 0.10366649]
 [0.64892476 0.11851314 0.57141507 0.84525476 0.46356412 0.8349542
  0.10385087 0.46227583 0.51524986 0.75499534]
 [0.38186626 0.01918366 0.51343985 0.95962872 0.14468523 0.3

###Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [14]:
# Array in question
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1
array_sum = x + y
print("1. \n", array_sum)

# 2
array_diff = x - y
print("2. \n", array_diff)

# 3
array_mul = x * 3
print("3. \n", array_mul)

# 4
array_square = np.square(x)
print("4. \n", array_square)

# 5
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("5. \n Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("6. \n Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

# 7
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("7. \n Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("Error:", e)
    print("\nExplanation: Here, NumPy tries to stack x and v row-wise , so both arrays must have the same number of columns. \nx has 2 columns, but v, being a 1D array (As it has only one row), doesn't naturally have a second dimension")


1. 
 [[ 6  8]
 [10 13]]
2. 
 [[-4 -4]
 [-4 -3]]
3. 
 [[ 3  6]
 [ 9 15]]
4. 
 [[ 1  4]
 [ 9 25]]
5. 
 Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
6. 
 Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: Here, NumPy tries to stack x and v row-wise , so both arrays must have the same number of columns. 
x has 2 columns, but v, being a 1D array (As it has only one row), doesn't naturally have a second dimension


###Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [15]:
# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1
A_inverse = np.linalg.inv(A)       # Inverse of A
identity_matrix = np.dot(A, A_inverse)
print("1. \n A.A⁻¹ = I:\n", identity_matrix)
print("Prove A.A⁻¹ = I: ", np.array_equal(identity_matrix, np.eye(2)))

# 2
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. \n AB:\n", AB)
print("BA:\n", BA)
print("Prove AB ≠ BA: ", not np.array_equal(AB, BA))

# 3
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("3. \n (AB)ᵀ:\n", AB_T)
print("BᵀAᵀ:\n", BT_AT)
print("Prove (AB)ᵀ = BᵀAᵀ: ", np.array_equal(AB_T, BT_AT))

# Solve the linear system using inverse methods
# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system as AX = B
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
rhs_vector = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
coeff_matrix_inv = np.linalg.inv(coeff_matrix)
solution = np.dot(coeff_matrix_inv, rhs_vector)
print("\nSolution to the system using inverse methods:\n", solution)

# Alternative: Use np.linalg.solve (more efficient)
solution_alt = np.linalg.solve(coeff_matrix, rhs_vector)
print("\nSolution to the system using np.linalg.solve function:\n", solution_alt)


1. 
 A.A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Prove A.A⁻¹ = I:  False
2. 
 AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Prove AB ≠ BA:  True
3. 
 (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Prove (AB)ᵀ = BᵀAᵀ:  True

Solution to the system using inverse methods:
 [ 2.  1. -2.]

Solution to the system using np.linalg.solve function:
 [ 2.  1. -2.]
